dist: xenial
services:
  - xvfb
addons:
  chrome: stable
language: node_js
sudo: required
notifications:
  email: false
node_js:
  - "10"
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
after_success:
  - npm run build
  - cp .git dist/ngx-electron-fresh/ -r
  - cp README.md dist/ngx-electron-fresh/
  - cd dist/ngx-electron-fresh/
  - npm install
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
